'use client';

import Link from 'next/link';
import dynamic from 'next/dynamic';
import { ArrowRight, Check, ChevronRight, Database, FlaskConical, GitBranch, LineChart, Search, ShieldCheck, Sparkles, Workflow } from 'lucide-react';
import { motion } from 'framer-motion';
import { researchAreas, projects, blogPosts } from '@/data/content';

const HeroVisualization = dynamic(() => import('@/components/hero/HeroVisualization'), { ssr: false });

const candles = [18, 24, 20, 30, 27, 35, 32, 44, 39, 48, 53, 47, 58, 64, 59, 68, 73, 70, 82, 78, 88, 94];
const researchSteps = [
  ['01', 'Data collection', 'Raw feeds, provenance, timestamps', Database],
  ['02', 'Data cleaning', 'Gaps, outliers, normalization', ShieldCheck],
  ['03', 'Feature engineering', 'Signals, regimes, derived fields', Workflow],
  ['04', 'Hypothesis', 'A falsifiable research question', FlaskConical],
  ['05', 'Backtest', 'Historical simulation with costs', LineChart],
  ['06', 'Validation', 'Walk-forward, Monte Carlo, OOS', GitBranch],
];

function Label({ children }: { children: React.ReactNode }) {
  return <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-[var(--text-muted)]">{children}</span>;
}

function Metric({ label, value, tone = 'default' }: { label: string; value: string; tone?: 'default' | 'positive' }) {
  return <div className="border-l border-[var(--border-color)] pl-4"><div className="font-mono text-[10px] uppercase tracking-wider text-[var(--text-muted)]">{label}</div><div className={tone === 'positive' ? 'mt-1 font-mono text-sm text-[var(--success)]' : 'mt-1 font-mono text-sm text-[var(--text-primary)]'}>{value}</div></div>;
}

function ProductTerminal() {
  return (
    <div className="terminal-shell overflow-hidden border border-[var(--border-color)] bg-[#0b0d10] shadow-[0_30px_100px_rgba(0,0,0,0.35)]">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--border-color)] px-4 py-3">
        <div className="flex items-center gap-3"><span className="size-2 rounded-full bg-[var(--success)]" /><span className="font-mono text-xs text-[var(--text-primary)]">RESEARCH MODE</span><span className="font-mono text-[10px] text-[var(--text-muted)]">/ XAUUSD</span></div>
        <div className="flex items-center gap-1">{['1M','5M','15M','1H','4H','1D'].map((t, i) => <button key={t} className={`px-2 py-1 font-mono text-[10px] ${i === 1 ? 'bg-[var(--accent-muted)] text-[var(--accent)]' : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]'}`}>{t}</button>)}</div>
      </div>
      <div className="grid lg:grid-cols-[1fr_250px]">
        <div className="relative min-h-[360px] border-b border-[var(--border-color)] p-4 lg:border-b-0 lg:border-r">
          <div className="absolute inset-0 opacity-70"><HeroVisualization /></div>
          <div className="relative z-10 flex items-start justify-between"><div><div className="font-mono text-[10px] text-[var(--text-muted)]">XAUUSD · 5 MIN</div><div className="mt-1 font-mono text-2xl text-[var(--text-primary)]">2,648.72 <span className="text-sm text-[var(--success)]">+0.84%</span></div></div><span className="rounded-sm border border-[var(--success)]/30 bg-[var(--success)]/10 px-2 py-1 font-mono text-[9px] text-[var(--success)]">LIVE SIMULATION</span></div>
          <svg viewBox="0 0 760 260" className="relative z-10 mt-5 h-[250px] w-full" role="img" aria-label="Illustrative XAUUSD research chart">
            <defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#a78bfa" stopOpacity=".22"/><stop offset="1" stopColor="#a78bfa" stopOpacity="0"/></linearGradient></defs>
            {[40, 90, 140, 190, 240].map(y => <line key={y} x1="0" x2="760" y1={y} y2={y} stroke="rgba(255,255,255,.07)" />)}
            <path d={`M 0 ${250 - candles[0] * 2} ${candles.map((v, i) => `L ${i * 36} ${250 - v * 2}`).join(' ')} L 760 260 L 0 260 Z`} fill="url(#chartFill)" />
            <path d={`M 0 ${250 - candles[0] * 2} ${candles.map((v, i) => `L ${i * 36} ${250 - v * 2}`).join(' ')}`} fill="none" stroke="#a78bfa" strokeWidth="2" />
            {candles.map((v, i) => <g key={i}><line x1={i * 36 + 8} x2={i * 36 + 8} y1={250 - v * 2 - 17} y2={250 - v * 2 + 17} stroke={i % 3 === 0 ? '#f87171' : '#34d399'} strokeOpacity=".75"/><rect x={i * 36 + 3} y={250 - v * 2 - (i % 3 === 0 ? 9 : 14)} width="10" height={i % 3 === 0 ? 18 : 28} fill={i % 3 === 0 ? '#f87171' : '#34d399'} fillOpacity=".7"/></g>)}
            <circle cx="510" cy="92" r="5" fill="#fbbf24"/><circle cx="510" cy="92" r="11" fill="none" stroke="#fbbf24" strokeOpacity=".35"/><text x="524" y="88" fill="#fbbf24" fontSize="10" fontFamily="monospace">SETUP DETECTED</text>
          </svg>
          <div className="relative z-10 flex gap-5 border-t border-[var(--border-color)] pt-3"><Metric label="Trend" value="Bullish" tone="positive"/><Metric label="Volatility" value="0.72"/><Metric label="Volume" value="1.84x"/></div>
        </div>
        <aside className="flex flex-col gap-4 p-4"><div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-wider text-[var(--text-muted)]">AI research copilot</span><Sparkles className="text-[var(--accent)]" size={14}/></div><div className="border border-[var(--border-color)] bg-[var(--bg-surface)] p-3"><div className="font-mono text-[10px] text-[var(--text-muted)]">OBSERVATION / 09:42:18</div><p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">Momentum is expanding above the session mean. Test continuation against the prior London range before drawing a conclusion.</p></div><div className="grid grid-cols-2 gap-2">{['Analyze market','Find setup','Build strategy','Backtest'].map(a => <button key={a} className="border border-[var(--border-color)] px-2 py-2 text-left text-[11px] text-[var(--text-secondary)] transition hover:border-[var(--accent)] hover:text-[var(--text-primary)]">{a}<ChevronRight size={12} className="float-right mt-0.5 text-[var(--accent)]"/></button>)}</div><div className="mt-auto border-t border-[var(--border-color)] pt-4"><Label>Backtest snapshot · illustrative</Label><div className="mt-3 grid grid-cols-2 gap-y-3"><Metric label="Trades" value="184"/><Metric label="Win rate" value="58.2%" tone="positive"/><Metric label="Profit factor" value="1.64"/><Metric label="Max drawdown" value="-8.4%"/></div></div></aside>
      </div>
    </div>
  );
}

export default function HomePage() {
  return <div className="bg-[var(--bg-primary)]">
    <section className="relative overflow-hidden border-b border-[var(--border-color)] pt-32 pb-20 lg:pt-44 lg:pb-28">
      <div className="absolute inset-0 opacity-35"><HeroVisualization /></div><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_35%,rgba(167,139,250,.12),transparent_32%),linear-gradient(90deg,var(--bg-primary)_10%,transparent_65%,var(--bg-primary)_100%)]" />
      <div className="relative mx-auto grid max-w-[1400px] gap-14 px-6 lg:grid-cols-[.88fr_1.12fr] lg:items-center lg:px-8"><div>
        <div className="mb-7 flex items-center gap-3"><span className="size-2 rounded-full bg-[var(--accent)] shadow-[0_0_14px_var(--accent)]"/><Label>Quantitative research · AI · market intelligence</Label></div>
        <h1 className="max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.055em] text-[var(--text-primary)] sm:text-6xl lg:text-[76px]">Researching intelligence <span className="text-[var(--accent)]">for markets.</span></h1>
        <p className="mt-7 max-w-xl text-lg leading-relaxed text-[var(--text-secondary)]">Elvaris builds quantitative research systems that combine market data, artificial intelligence, statistical methods, and systematic validation.</p>
        <div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/research" className="group inline-flex items-center gap-2 bg-[var(--accent)] px-5 py-3 text-sm font-medium text-black transition hover:bg-[#c4b5fd]">Explore platform <ArrowRight size={15} className="transition group-hover:translate-x-1"/></Link><Link href="/blog" className="inline-flex items-center gap-2 border border-[var(--border-color)] px-5 py-3 text-sm text-[var(--text-primary)] transition hover:border-[var(--text-muted)]">View research</Link><Link href="/documentation/introduction" className="ml-1 text-xs text-[var(--text-muted)] underline-offset-4 hover:text-[var(--text-primary)] hover:underline">Read methodology →</Link></div>
        <div className="mt-12 grid max-w-lg grid-cols-3 gap-5 border-t border-[var(--border-color)] pt-5"><Metric label="Research areas" value="06"/><Metric label="Active projects" value="04"/><Metric label="Methodology" value="OOS-first"/></div>
      </div><div className="relative"><div className="absolute -inset-8 rounded-full bg-[var(--accent)]/5 blur-3xl"/><ProductTerminal/></div></div>
    </section>
    <div className="border-b border-[var(--border-color)] bg-[var(--bg-surface)]"><div className="mx-auto flex max-w-[1400px] flex-wrap items-center justify-center gap-x-8 gap-y-3 px-6 py-5 font-mono text-[10px] uppercase tracking-[.16em] text-[var(--text-muted)] lg:justify-between lg:px-8">{['Quantitative research','AI / ML','Market data','Backtesting','Risk analysis','Statistical validation'].map(item => <span key={item} className="flex items-center gap-3"><Check size={12} className="text-[var(--accent)]"/>{item}</span>)}</div></div>
    <section className="mx-auto max-w-[1400px] px-6 py-24 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><Label>Research operating system</Label><h2 className="mt-5 max-w-lg text-4xl font-semibold leading-tight tracking-[-.04em] lg:text-5xl">From market data to researched evidence.</h2><p className="mt-6 max-w-md text-base leading-relaxed text-[var(--text-secondary)]">A rigorous environment for asking better questions, testing ideas honestly, and making the work reproducible from first observation to final result.</p><Link href="/about" className="mt-8 inline-flex items-center gap-2 text-sm text-[var(--accent)] hover:gap-3">How Elvaris works <ArrowRight size={14}/></Link></div><div className="grid border-l border-t border-[var(--border-color)] sm:grid-cols-2 lg:grid-cols-3">{researchSteps.map(([num, title, desc, Icon], i) => { const StepIcon = Icon as React.ComponentType<{size?: number; className?: string}>; return <motion.div key={num as string} whileHover={{ backgroundColor: 'rgba(167,139,250,.04)' }} className="min-h-[190px] border-b border-r border-[var(--border-color)] p-5"><div className="flex items-center justify-between"><span className="font-mono text-xs text-[var(--accent)]">{num as string}</span><StepIcon size={16} className="text-[var(--text-muted)]"/></div><h3 className="mt-12 text-base font-medium text-[var(--text-primary)]">{title as string}</h3><p className="mt-2 text-xs leading-relaxed text-[var(--text-muted)]">{desc as string}</p></motion.div>})}</div></div></section>
    <section className="border-y border-[var(--border-color)] bg-[var(--bg-surface)]"><div className="mx-auto max-w-[1400px] px-6 py-24 lg:px-8 lg:py-32"><div className="flex flex-wrap items-end justify-between gap-6"><div><Label>Research areas</Label><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] lg:text-5xl">The intelligence layer.</h2></div><Link href="/research" className="inline-flex items-center gap-2 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)]">Explore all research <ArrowRight size={14}/></Link></div><div className="mt-14 grid border-l border-t border-[var(--border-color)] md:grid-cols-2 lg:grid-cols-3">{researchAreas.map(area => <Link href={`/research/${area.slug}`} key={area.slug} className="group min-h-[210px] border-b border-r border-[var(--border-color)] p-6 transition hover:bg-[var(--bg-hover)]"><div className="flex justify-between"><span className="font-mono text-xs text-[var(--accent)]">{area.id}</span><ArrowRight size={16} className="text-[var(--text-muted)] transition group-hover:translate-x-1 group-hover:text-[var(--accent)]"/></div><h3 className="mt-12 text-lg font-medium text-[var(--text-primary)]">{area.title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-[var(--text-secondary)]">{area.shortDescription}</p></Link>)}</div></div></section>
    <section className="mx-auto max-w-[1400px] px-6 py-24 lg:px-8 lg:py-32"><div className="flex flex-wrap items-end justify-between gap-6"><div><Label>Selected work</Label><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] lg:text-5xl">Research in motion.</h2></div><Link href="/projects" className="inline-flex items-center gap-2 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)]">View projects <ArrowRight size={14}/></Link></div><div className="mt-12 divide-y divide-[var(--border-color)] border-y border-[var(--border-color)]">{projects.slice(0, 4).map(project => <Link href={`/projects/${project.slug}`} key={project.slug} className="group grid gap-4 py-7 transition hover:bg-[var(--bg-surface)] sm:grid-cols-[80px_1fr_220px] sm:items-center"><span className="font-mono text-xs text-[var(--accent)]">{project.id}</span><div><h3 className="text-xl font-medium text-[var(--text-primary)] group-hover:text-[var(--accent)]">{project.title}</h3><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">{project.description}</p></div><div className="flex items-center justify-between gap-3 sm:justify-end"><span className="font-mono text-[10px] uppercase tracking-wider text-[var(--text-muted)]">{project.status}</span><ArrowRight size={16} className="text-[var(--text-muted)] transition group-hover:translate-x-1 group-hover:text-[var(--accent)]"/></div></Link>)}</div></section>
    <section className="border-t border-[var(--border-color)] bg-[var(--bg-surface)]"><div className="mx-auto grid max-w-[1400px] gap-12 px-6 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-32"><div><Label>Research notes</Label><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] lg:text-5xl">Methods over mythology.</h2><p className="mt-6 max-w-md text-base leading-relaxed text-[var(--text-secondary)]">Practical writing on markets, models, data quality, and the discipline required to trust a result.</p><Link href="/blog" className="mt-8 inline-flex items-center gap-2 text-sm text-[var(--accent)]">Read the publication <ArrowRight size={14}/></Link></div><div className="divide-y divide-[var(--border-color)] border-y border-[var(--border-color)]">{blogPosts.slice(0, 3).map(post => <Link href={`/blog/${post.slug}`} key={post.slug} className="group flex items-center justify-between gap-6 py-6"><div><div className="font-mono text-[10px] uppercase tracking-wider text-[var(--accent)]">{post.category}</div><h3 className="mt-2 text-lg text-[var(--text-primary)] group-hover:text-[var(--accent)]">{post.title}</h3><p className="mt-1 text-sm text-[var(--text-muted)]">{post.readingTime} · {post.date}</p></div><ArrowRight size={16} className="shrink-0 text-[var(--text-muted)] transition group-hover:translate-x-1 group-hover:text-[var(--accent)]"/></Link>)}</div></div></section>
    <section className="mx-auto max-w-[1400px] px-6 py-24 text-center lg:px-8 lg:py-32"><Label>Build a better research loop</Label><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-semibold tracking-[-.045em] lg:text-6xl">The market is noisy. Your method does not have to be.</h2><p className="mx-auto mt-6 max-w-xl text-base text-[var(--text-secondary)]">Explore the platform, read the methodology, and follow the work as Elvaris turns market complexity into researched evidence.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/research" className="inline-flex items-center gap-2 bg-[var(--accent)] px-5 py-3 text-sm font-medium text-black hover:bg-[#c4b5fd]">Explore platform <ArrowRight size={15}/></Link><Link href="/contact" className="inline-flex items-center gap-2 border border-[var(--border-color)] px-5 py-3 text-sm text-[var(--text-primary)] hover:border-[var(--text-muted)]">Contact Elvaris <ArrowRight size={15}/></Link></div></section>
  </div>;
}
